MERCHANDISERS/MERCHANDISERS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
]+ static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

MERCHANDISERS/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
       path("", views.intro_page, name="intro_page"),
       path("home", views.index, name="index_page"),
       
       path("ask/question/", views.ask_question_page, name="ask_question_page"),
       path("answers/details/<question_id>/", views.answers_details_page, name="answers_details_page"),
       path("answers/details/<question_id>/<answer_id>/", views.answers_details_page2, name="answers_details_page2"),

       path("edit/profile/<user_id>/", views.edit_profile, name="edit_profile_page"),
       path("my/profile/", views.my_profile, name="my_profile_page"),
       path("my/questions/", views.my_questions, name="my_questions_page"),
       path("my/answers/", views.my_answers, name="my_answers_page"),

       path("others/profile/<user_id>/", views.others_profile, name="others_profile_page"),
       path("others/questions/<user_id>/", views.others_questions, name="others_questions_page"),
       path("others/answers/<user_id>/", views.others_answers, name="others_answers_page"),

       path("delete/question/<question_id>/", views.delete_question, name="delete_question"),
       path("edit/question/<question_id>/", views.edit_question, name="edit_question_page"),

       path("delete/answer/<answer_id>/", views.delete_answer, name="delete_answer"),
       path("edit/answer/<answer_id>/", views.edit_answer, name="edit_answer_page"),

       path("up/vote/question/<question_id>/", views.upvote_question, name="upgrade_question"),
       path("down/vote/question/<question_id>/", views.downvote_question, name="downgrade_question"),
       path("cancel/question/vote/<question_id>/", views.cancel_question_vote, name="cancel_question_vote"),

       path("upgrade/answer/<question_id>/<answer_id>/", views.upvote_answer, name="upgrade_answer"),
       path("downgrade/answer/<question_id>/<answer_id>/", views.downvote_answer, name="downgrade_answer"),
       path("cancel/answer/vote/<question_id>/<answer_id>/", views.cancel_answer_vote, name="cancel_answer_vote"),


]

MERCHANDISERS/main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Question(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=1024)
    details = models.TextField()
    asked_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.title} "
    

    
class Answer(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.TextField()
    answered_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.user} : {self.question.title}"
    

    

class QuestionScore(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    is_rated_up = models.BooleanField(default=False)
    is_rated_down = models.BooleanField(default=False)



class AnswerScore(models.Model):

    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    is_rated_up = models.BooleanField(default=False)
    is_rated_down = models.BooleanField(default=False)



    

MERCHANDISERS/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from .models import Question, Answer, QuestionScore, AnswerScore
from django.contrib.auth.models import User
from accounts.models import Profile


# Create your views here.
 
def index(request : HttpRequest):
   ''' Display the homepage with all answers and the user can search for a specific question '''

   questions = Question.objects.all()

   if 'search' in request.GET:
      questions = Question.objects.filter(title__contains=request.GET["search"])
   return  render(request, "main/index.html",{"questions": questions})



def intro_page(request : HttpRequest):
   ''' introduction page when the website loading'''
   return render(request, "main/intro.html")



def ask_question_page(request : HttpRequest):
   ''' Provide a form for user to Ask his question '''
   if not request.user.is_authenticated:
      return redirect("accounts:login_register_user")

   if request.method == "POST":
      #to add a new entry
      new_question = Question(user = request.user, title= request.POST["title"], details = request.POST["details"])
      new_question.save()
      return redirect("main:index_page")

   return render(request, "main/ask_question.html")



def answers_details_page(request : HttpRequest, question_id):
   ''' Display question details and all it's answers '''

   question = Question.objects.get(id=question_id)
   question_score = QuestionScore.objects.filter(question=question, is_rated_up=True).count() - QuestionScore.objects.filter(question=question, is_rated_up=False).count()
  

   if request.method == "POST":
      #to add a new entry
      new_answer = Answer(user = request.user, question=question, answer = request.POST["answer"])
      new_answer.save()
      return redirect("main:answers_details_page", question_id = question_id)
   
   answers = Answer.objects.filter(question = question)
   answers_number = Answer.objects.filter(question = question).count()

   return render(request, "main/answers_details.html", {"question" : question, "answers" : answers, "answers_number" : answers_number, "question_score" : question_score})



def my_profile(request : HttpRequest):
   ''' Diaplsy the user's profile '''

   if not request.user.is_authenticated:
      return redirect("main:index_page")

   questions_number = Question.objects.filter(user = request.user).count()
   answers_number = Answer.objects.filter(user = request.user).count()

   questions = Question.objects.filter(user = request.user)
   total_questios_score = 0
   for question in questions:
      question_score = QuestionScore.objects.filter(question=question, is_rated_up=True).count() - QuestionScore.objects.filter(question=question, is_rated_up=False).count()
      total_questios_score += question_score

   answers = Answer.objects.filter(user = request.user)
   total_answers_score = 0
   for answer in answers:
      answer_score = AnswerScore.objects.filter(answer=answer, is_rated_up=True).count() - AnswerScore.objects.filter(answer=answer, is_rated_up=False).count()
      total_answers_score += answer_score
   
   total_user_score = total_questios_score + total_answers_score

   return render(request, "main/my_profile.html",{"questions_number" : questions_number,"answers_number" : answers_number, "total_user_score" : total_user_score})



def edit_profile(request : HttpRequest, user_id):
   edit_msg = None

   if not request.user.is_authenticated:
      return redirect("main:index_page")

   user = User.objects.get(id=user_id)
   user_profile = Profile.objects.filter(user = user).first()
   if request.method == "POST":
      try :
         user_profile.user.username = request.POST["username"]
         user_profile.user.email = request.POST["email"]
         user_profile.about = request.POST["about"]
         if "profile_image" in request.FILES:
            user_profile.profile_image = request.FILES["profile_image"]

         user_profile.user.save()
         user_profile.save()

         if request.user.is_staff :
            return redirect("main:others_profile_page", user_id)
         else :
            return redirect("main:my_profile_page")
      except : 
         edit_msg = "Username taken, Please use another one"

   
   
   
   return render(request, "main/edit_profile.html", {"user_profile" : user_profile, "edit_msg" : edit_msg})



def my_questions(request : HttpRequest):
   ''' Display all user's questions '''

   if not request.user.is_authenticated:
      return redirect("main:index_page")

   questions = Question.objects.filter(user = request.user)
   questions_number = Question.objects.filter(user = request.user).count()
   

   if 'search' in request.GET:
      questions = Question.objects.filter(title__contains=request.GET["search"])
   

   return render(request, "main/my_questions.html",{"questions" : questions, "questions_number" : questions_number})



def my_answers(request : HttpRequest):
   ''' Display all user's questions '''

   if not request.user.is_authenticated:
      return redirect("main:index_page")

   answers = Answer.objects.filter(user = request.user)
   answers_number = Answer.objects.filter(user = request.user).count()

   return render(request, "main/my_answers.html",{"answers" : answers, "answers_number" : answers_number})



def others_profile(request : HttpRequest, user_id):
   ''' Display other user profile '''

   user = User.objects.get(id=user_id)
   questions_number = Question.objects.filter(user = user).count()
   answers_number = Answer.objects.filter(user = user).count()

   questions = Question.objects.filter(user = user)
   total_questios_score = 0
   for question in questions:
      question_score = QuestionScore.objects.filter(question=question, is_rated_up=True).count() - QuestionScore.objects.filter(question=question, is_rated_up=False).count()
      total_questios_score += question_score

   answers = Answer.objects.filter(user = user)
   total_answers_score = 0
   for answer in answers:
      answer_score = AnswerScore.objects.filter(answer=answer, is_rated_up=True).count() - AnswerScore.objects.filter(answer=answer, is_rated_up=False).count()
      total_answers_score += answer_score
   
   total_user_score = total_questios_score + total_answers_score


   

   return render(request, "main/others_profile.html",{"user" : user, "questions_number" : questions_number, "answers_number" : answers_number, "total_user_score" : total_user_score})



def others_questions(request : HttpRequest, user_id):
   ''' Dispaly other users questions '''

   user = User.objects.get(id=user_id)
   questions = Question.objects.filter(user = user)
   questions_number = Question.objects.filter(user = user).count()


   return render(request, "main/others_questions.html",{"questions" : questions, "questions_number" : questions_number, "user" : user})



def others_answers(request : HttpRequest, user_id):
   ''' Display other users answers '''

   user = User.objects.get(id=user_id)
   answers = Answer.objects.filter(user = user)
   answers_number = Answer.objects.filter(user = user).count()

   return render(request, "main/others_answers.html",{"answers" : answers, "answers_number" : answers_number, "user" : user})



def delete_question(request : HttpRequest, question_id):
    ''' User can delete his questions '''

    if not request.user.is_authenticated:
      return redirect("main:index_page")

    question = Question.objects.get(id=question_id)
    question.delete()
    if request.user.is_staff:
        return redirect("main:index_page")
    return redirect("main:my_questions_page")



def edit_question(request : HttpRequest, question_id):
    ''' User can can edit his questions '''

    if not request.user.is_authenticated:
      return redirect("main:index_page")


    question = Question.objects.get(id=question_id)

    if request.method == "POST":
        question.title = request.POST["title"]
        question.details = request.POST["details"]
        question.save()
        return redirect("main:my_questions_page")

    return render(request, "main/edit_question.html", {"question" : question})
   


def delete_answer(request : HttpRequest, answer_id):
    ''' User cane delete his answers '''

    if not request.user.is_authenticated:
      return redirect("main:index_page")

    answer = Answer.objects.get(id=answer_id)
    answer.delete()
    if request.user.is_staff:
        return redirect("main:index_page")
    return redirect("main:my_answers_page")



def edit_answer(request : HttpRequest, answer_id : int):
    ''' User can can edit his questions '''

    if not request.user.is_authenticated:
      return redirect("main:index_page")

    answer = Answer.objects.get(id=answer_id)

    if request.method == "POST":
        answer.answer = request.POST["answer"]
        answer.save()
        return redirect("main:my_answers_page")

    return render(request, "main/edit_answer.html", {"answer" : answer})



def upvote_question(request : HttpRequest, question_id: int):
   ''' give the question 1 point up '''

   if not request.user.is_authenticated:
      return redirect("main:index_page")

   question = Question.objects.get(id=question_id)
   question_score  = QuestionScore.objects.filter(user=request.user, question=question).first()

   if question_score:
      question_score.is_rated_up = True
      question_score.is_rated_down = False
      question_score.save()
   else:
      new_score = QuestionScore(user = request.user, question=question)
      new_score.is_rated_up = True
      new_score.save()

   return redirect("main:answers_details_page", question_id = question_id)



def downvote_question(request : HttpRequest, question_id: int):
   ''' take from the question 1 point  '''

   if not request.user.is_authenticated:
      return redirect("main:index_page")

   question = Question.objects.get(id=question_id)

MERCHANDISERS/main/templates/main/answers_details.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}   Question's answers  {% endblock %}


{% block content %}

<main class="container">
    <div class="row g-5">
        <div class="col-md-8">
            <!-- ######### Question Section Start ############ -->
            <div class="container ms-3">    
                <div class="row">
                        <div class="col-1 pt-4">
                            {% if request.user.is_authenticated %}
                                <!------------- Start Upvote Question ---------------->
                                <a href="{% url 'main:upgrade_question' question.id %}" data-toggle="tooltip" title="This question is useful">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-caret-up" viewBox="0 0 16 16">
                                        <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z"/>
                                    </svg>
                                </a>
                                <!------------- End Upvote Question ---------------->
                                <h5 style="margin-left: 15px;">{{ question_score }}</h5>
                                <!------------- Start Downvote Question ------------->
                                <a href="{% url 'main:downgrade_question' question.id %}" data-toggle="tooltip" title="This question is not useful">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-caret-down" viewBox="0 0 16 16" >
                                        <path d="M3.204 5h9.592L8 10.481 3.204 5zm-.753.659 4.796 5.48a1 1 0 0 0 1.506 0l4.796-5.48c.566-.647.106-1.659-.753-1.659H3.204a1 1 0 0 0-.753 1.659z"/>
                                    </svg>
                                </a>
                                <!------------- End Downvote Question ---------------->
                                <a href="{% url 'main:cancel_question_vote' question.id %} " style="margin-left: 10px;" data-toggle="tooltip" title="cancel my vote">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                    </svg>
                                </a>
                            {% endif %}
                        </div>

                        <div class="col-10 pt-5">
                            <div class="post-preview mb-5 ">
                                <h2 class="post-title">{{ question.title}}</h2>
                                <p style="font-size: small;" class="post-meta">
                                    Asked by
                                    <a href="{% url 'main:others_profile_page'  question.user.id  %}"> 
                                        <strong>{{ question.user.username}}</strong> 
                                    </a>
                                    on {{ question.asked_at}}
                                </p>

                                <h4> {{ question.details }}</h4>    
                            </div>         
                        </div>  
                       <!-- ----------- Delete Question ----------- -->
                        <div class="col-1 mt-5">
                            {% if request.user.is_staff %}
                              <a  href="{% url 'main:delete_question' question.id %}" style="display: inline;">
                                <button type="button" class="btn btn-outline-danger">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"></path>
                                  </svg>
                                </button>
                              </a>
                            {% endif %}
                        </div>   
                    <hr class="my-4"/>     
                </div>
            </div>

            <!-- ######### Question Section End ############ -->



            <!-- ######### Answers Section Start ############ -->
            <div class="container ms-3 mt-5 ">
                <h4 class="mb-5"> {{ answers_number }} Answers</h4>
                {% for answer in answers %}
                    <div class="row">
                        <div class="col-1 pt-1">
                            {% if request.user.is_authenticated %}
                                <!------------- Start Upvote Answer ---------------->
                                <a href="{% url 'main:upgrade_answer' question.id answer.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-caret-up" viewBox="0 0 16 16">
                                        <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z"/>
                                    </svg>
                                </a>
                                <!------------- End Upvote Answer ---------------->
                                <h5 style="margin-left: 15px; font-size: medium;">{% if answer == voted_answer %}{{ answer_score }} {% endif %}</h5>
                                <!------------- Start Downvote Answer ------------->
                                <a href="{% url 'main:downgrade_answer' question.id answer.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-caret-down" viewBox="0 0 16 16">
                                        <path d="M3.204 5h9.592L8 10.481 3.204 5zm-.753.659 4.796 5.48a1 1 0 0 0 1.506 0l4.796-5.48c.566-.647.106-1.659-.753-1.659H3.204a1 1 0 0 0-.753 1.659z"/>
                                    </svg>
                                </a>
                                <!------------- End Downvote Answer ---------------->
                                <a href="{% url 'main:cancel_answer_vote' question.id answer.id %} " style="margin-left: 3px;" data-toggle="tooltip" title="cancel my vote">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                    </svg>
                                </a>
                            {% endif %}
                        </div>
                        
                        <div class="col-10 pt-4">
                            <div class="post-preview">
                                <p>{{ answer.answer }}</p>
                                <p style="font-size: small;" class="post-meta">
                                    Answered by
                                    <a href="{% url 'main:others_profile_page'  answer.user.id  %}">
                                        <strong>{{ answer.user.username}}</strong>
                                    </a>
                                    on {{ answer.answered_at}}
                                </p>
                            </div>
                        </div>
                        <!-- ------- Delete Answer --------- -->
                        <div class="col-1 mt-5"  >
                            {% if request.user.is_staff %}
                            <a  href="{% url 'main:delete_answer' answer.id %}" style="display: inline;">
                                <button type="button" class="btn btn-outline-danger">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"></path>
                                </svg>
                                </button>
                            </a>
                            {% endif %}
                        </div>
                        <hr class="my-4" style="width: 700px;" />
                    </div>
                {% endfor %}
            </div>

        <!-- ######### Answers Section End ############ -->



        <!-- ######### Post Answer Section Start ############ -->
        <div id="container">
            <form method="post" action="" > 
                {% csrf_token %}
                <div class="container" style="padding: 20px;">
                    
                    <div class="mb-3">
                        <label for="Answer" class="form-label">Your Answer</label>
                        <textarea name="answer" style="height: 200px;" class="form-control"  rows="3" required></textarea>
                    </div>
                </div>
                <button class="btn btn-primary ms-5" type="submit">Post Your Answer</button>
        
            </form>
        </div>
        <!-- ######### Post Answer Section End ############ -->
        </div>

        <!-- ################# Navigation Sidbar Start ################## -->
        <div class="col-6 col-md-4" style="margin-top: 140px;">
            <div class="position-sticky bg-light rounded" style="top: 2rem;">
                <div class="p-4 mb-3">
                    <ul class="list-group  bg-transparent  list-group-flush " >
                        <a href="{% url 'main:index_page' %}">
                            <li class="list-group-item  bg-transparent border-0 ">
                                <svg xmlns="http://www.w3.org/2000/svg" style="margin-right:5px;" width="16" height="16" fill="currentColor" class="bi bi-globe-americas" viewBox="0 0 16 16">
                                    <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0ZM2.04 4.326c.325 1.329 2.532 2.54 3.717 3.19.48.263.793.434.743.484-.08.08-.162.158-.242.234-.416.396-.787.749-.758 1.266.035.634.618.824 1.214 1.017.577.188 1.168.38 1.286.983.082.417-.075.988-.22 1.52-.215.782-.406 1.48.22 1.48 1.5-.5 3.798-3.186 4-5 .138-1.243-2-2-3.5-2.5-.478-.16-.755.081-.99.284-.172.15-.322.279-.51.216-.445-.148-2.5-2-1.5-2.5.78-.39.952-.171 1.227.182.078.099.163.208.273.318.609.304.662-.132.723-.633.039-.322.081-.671.277-.867.434-.434 1.265-.791 2.028-1.12.712-.306 1.365-.587 1.579-.88A7 7 0 1 1 2.04 4.327Z"/>
                                </svg>
                                Questions
                            </li>
                        </a>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'main:my_questions_page' %}">
                                <li class="list-group-item  bg-transparent border-0" style="margin-left: 25px;">
                                    My Questions
                                </li>
                            </a>
                            <a href="{% url 'main:my_answers_page' %}">
                                <li class="list-group-item  bg-transparent border-0" style="margin-left: 25px;">
                                    My Answers
                                </li>
                            </a>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <!-- ################# Navigation Sidbar Section End ################## -->

    </div>
</main>

  


{% endblock %}

MERCHANDISERS/main/templates/main/my_profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %} My Profile {% endblock %}


{% block content %}

<div class="row py-5 px-4">
    <div class="col-md-5 mx-auto"> <!-- Profile widget --> 
        <div class="bg-white shadow rounded overflow-hidden"> 
            <div class="px-4 pt-0 pb-4 cover"> 
                <div class="media align-items-end profile-head"> 
                    <div class="profile mr-3">
                        <h3 style="position: absolute; margin:20px 0 0 160px; color: white;">{{ user.username }}</h3>
                        <p style="position: absolute; margin:50px 0 0 170px; color: white; font-size: small;">Score: {{ total_user_score }} </p>
                        <img src="{{ request.user.profile.profile_image.url}}" style="height: 130px; width: 130px;" alt="{{user.username}} image"  class="rounded mb-2 img-thumbnail">  
                    </div> 
                </div> 
            </div> 
            <a href="{% url 'main:edit_profile_page' user.id%}" class="btn btn-outline-dark btn-sm btn-block" style="margin: 60px 0px 0px 25px; width: 130px;">Edit profile</a>
            <div class="bg-light p-4 d-flex justify-content-end text-center"> 
                <p style="margin-right: 26%;">Email: {{user.email}} </p>
                <ul class="list-inline mb-0"> 
                    <li class="list-inline-item"> 
                        <a href="{% url 'main:my_questions_page' %}">
                            <h5 class="font-weight-bold mb-0 d-block">{{ questions_number }}</h5>
                            <small class="text-muted"> <i class="fas fa-user mr-1"></i>Questions</small> 
                        </a>
                    </li> 
                    <li class="list-inline-item"> 
                        <a href="{% url 'main:my_answers_page' %}">
                            <h5 class="font-weight-bold mb-0 d-block">{{answers_number}}</h5>
                            <small class="text-muted"> <i class="fas fa-user mr-1"></i>Answers</small> 
                        </a>
                    </li> 
                </ul> 
            </div> 
            <div class="px-4 py-3"> 
                <h5 class="mb-0">About</h5> 
                <div class="p-4 rounded shadow-sm bg-light"> 
                    <p class="font-italic mb-0">{{ user.profile.about }}</p> 
                    
                </div> 
            </div>     
        </div> 
    </div>
</div>


{% endblock %}